POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Ramya",
  "email": "ramyagandhi16@gmail.com",
  "address": "pudukkottai",
  "dateOfBirth": "2001-10-16",
  "registeredDate": "2025-03-30"
}